# Generated by Django 6.0.3 on 2026-09-24 13:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL Slug')),
                ('marka', models.CharField(db_index=True, max_length=60, verbose_name='Marka')),
                ('seri', models.CharField(blank=True, max_length=80, verbose_name='Seri')),
                ('model', models.CharField(db_index=True, max_length=120, verbose_name='Model')),
                ('kasa_tipi', models.CharField(choices=[('-', 'Belirtilmemiş'), ('Cabrio', 'Cabrio'), ('Coupe', 'Coupe'), ('Hatchback/3', 'Hatchback 3 Kapı'), ('Hatchback/5', 'Hatchback 5 Kapı'), ('MPV', 'MPV'), ('Pick-up', 'Pick-up'), ('Roadster', 'Roadster'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Station wagon', 'Station Wagon')], db_index=True, default='-', max_length=20, verbose_name='Kasa Tipi')),
                ('vites_tipi', models.CharField(choices=[('Düz', 'Düz'), ('Otomatik', 'Otomatik'), ('Yarı Otomatik', 'Yarı Otomatik')], db_index=True, max_length=20, verbose_name='Vites Tipi')),
                ('yakit_tipi', models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik'), ('Hibrit', 'Hibrit'), ('LPG & Benzin', 'LPG & Benzin')], db_index=True, max_length=20, verbose_name='Yakıt Tipi')),
                ('cekis', models.CharField(blank=True, choices=[('4WD (Sürekli)', '4WD (Sürekli)'), ('AWD (Elektronik)', 'AWD (Elektronik)'), ('Arkadan İtiş', 'Arkadan İtiş'), ('Önden Çekiş', 'Önden Çekiş')], max_length=25, verbose_name='Çekiş')),
                ('motor_hacmi', models.PositiveIntegerField(blank=True, choices=[(900, '900 cc'), (1000, '1000 cc'), (1100, '1100 cc'), (1200, '1200 cc'), (1250, '1250 cc'), (1300, '1300 cc'), (1400, '1400 cc'), (1500, '1500 cc'), (1600, '1600 cc'), (1700, '1700 cc'), (1800, '1800 cc'), (1900, '1900 cc'), (2000, '2000 cc'), (2100, '2100 cc'), (2200, '2200 cc'), (2300, '2300 cc'), (2400, '2400 cc'), (2500, '2500 cc'), (2600, '2600 cc'), (2700, '2700 cc'), (2800, '2800 cc'), (2900, '2900 cc'), (3000, '3000 cc')], null=True, verbose_name='Motor Hacmi (cc)')),
                ('motor_gucu', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(2000)], verbose_name='Motor Gücü (HP)')),
                ('yil', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2030)], verbose_name='Model Yılı')),
                ('kilometre', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500000)], verbose_name='Kilometre')),
                ('renk', models.CharField(blank=True, choices=[('Bej', 'Bej'), ('Beyaz', 'Beyaz'), ('Bordo', 'Bordo'), ('Diger', 'Diğer'), ('Füme', 'Füme'), ('Gri', 'Gri'), ('Kahverengi', 'Kahverengi'), ('Kırmızı', 'Kırmızı'), ('Lacivert', 'Lacivert'), ('Mavi', 'Mavi'), ('Siyah', 'Siyah'), ('Yeşil', 'Yeşil'), ('Şampanya', 'Şampanya')], max_length=20, verbose_name='Renk')),
                ('tramer_kategori', models.CharField(choices=[('yok', 'Yok'), ('dusuk', 'Düşük'), ('orta', 'Orta'), ('yuksek', 'Yüksek'), ('bilinmiyor', 'Bilinmiyor')], default='bilinmiyor', max_length=15, verbose_name='Tramer Kategori')),
                ('tramer_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tramer Tutarı (TL)')),
                ('boyali_sayisi', models.PositiveSmallIntegerField(default=0, verbose_name='Boyalı Parça Sayısı')),
                ('degisen_sayisi', models.PositiveSmallIntegerField(default=0, verbose_name='Değişen Parça Sayısı')),
                ('sehir', models.CharField(db_index=True, max_length=50, verbose_name='Şehir')),
                ('kimden', models.CharField(choices=[('Galeriden', 'Galeriden'), ('Sahibinden', 'Sahibinden'), ('Yetkili Bayiden', 'Yetkili Bayiden')], db_index=True, default='Sahibinden', max_length=20, verbose_name='Kimden')),
                ('fiyat', models.DecimalField(db_index=True, decimal_places=2, max_digits=14, verbose_name='Fiyat (TL)')),
                ('ai_tahmin_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='AI Tahmin Fiyatı')),
                ('ai_sapma_yuzdesi', models.FloatField(blank=True, null=True, verbose_name='AI Sapma %')),
                ('firsat_skoru', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Fırsat Skoru (0-100)')),
                ('satici_adi', models.CharField(blank=True, max_length=150, verbose_name='Satıcı Adı')),
                ('yetkili_kisi', models.CharField(blank=True, max_length=100, verbose_name='Yetkili Kişi')),
                ('satici_tipi', models.CharField(blank=True, max_length=60, verbose_name='Satıcı Tipi')),
                ('yetki_belge_no', models.CharField(blank=True, max_length=30, verbose_name='Yetki Belge No')),
                ('boya_degisen_detay', models.TextField(blank=True, verbose_name='Boya/Değişen Detay')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('satildi', 'Satıldı'), ('onay', 'Onay Bekliyor')], db_index=True, default='onay', max_length=10, verbose_name='Durum')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('one_cikan', models.BooleanField(db_index=True, default=False, verbose_name='Öne Çıkan')),
                ('ilan_tarihi', models.DateField(auto_now_add=True, db_index=True, verbose_name='İlan Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('satici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'db_table': 'ml_model_ilanmodel',
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='IlanFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(upload_to='ilan_fotolar/%Y/%m/', verbose_name='Fotoğraf')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('kapak', models.BooleanField(default=False, verbose_name='Kapak Fotoğrafı')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotolar', to='listings.ilanmodel', verbose_name='İlan')),
            ],
            options={
                'verbose_name': 'İlan Fotoğrafı',
                'verbose_name_plural': 'İlan Fotoğrafları',
                'db_table': 'ml_model_ilanfoto',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='FavoriModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriler', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriler', to='listings.ilanmodel', verbose_name='İlan')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoriler',
                'db_table': 'ml_model_favorimodel',
            },
        ),
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('konu', models.CharField(choices=[('genel', 'Genel Soru'), ('teknik', 'Teknik Destek'), ('ilan', 'İlan Sorunu'), ('odeme', 'Ödeme Sorunu'), ('diger', 'Diğer')], db_index=True, default='genel', max_length=10, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(db_index=True, default=False, verbose_name='Okundu')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iletisimler', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim Mesajları',
                'db_table': 'ml_model_iletisimmodel',
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.AddIndex(
            model_name='ilanmodel',
            index=models.Index(fields=['marka', 'model'], name='ml_model_il_marka_38a578_idx'),
        ),
        migrations.AddIndex(
            model_name='ilanmodel',
            index=models.Index(fields=['yil', 'kilometre'], name='ml_model_il_yil_7e60d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ilanmodel',
            index=models.Index(fields=['sehir', 'durum'], name='ml_model_il_sehir_672577_idx'),
        ),
        migrations.AddIndex(
            model_name='ilanmodel',
            index=models.Index(fields=['fiyat'], name='ml_model_il_fiyat_e0d994_idx'),
        ),
        migrations.AddIndex(
            model_name='ilanmodel',
            index=models.Index(fields=['is_active', 'durum'], name='ml_model_il_is_acti_a6b1df_idx'),
        ),
        migrations.AddIndex(
            model_name='ilanmodel',
            index=models.Index(fields=['one_cikan', 'is_active'], name='ml_model_il_one_cik_ef0122_idx'),
        ),
        migrations.AddIndex(
            model_name='ilanfoto',
            index=models.Index(fields=['ilan', 'kapak'], name='ml_model_il_ilan_id_1ebca2_idx'),
        ),
        migrations.AddIndex(
            model_name='favorimodel',
            index=models.Index(fields=['kullanici', 'ilan'], name='ml_model_fa_kullani_e64731_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorimodel',
            unique_together={('kullanici', 'ilan')},
        ),
        migrations.AddIndex(
            model_name='iletisimmodel',
            index=models.Index(fields=['okundu', 'olusturuldu'], name='ml_model_il_okundu_cdec11_idx'),
        ),
        migrations.AddIndex(
            model_name='iletisimmodel',
            index=models.Index(fields=['konu'], name='ml_model_il_konu_ea6065_idx'),
        ),
    ]
