# Generated by Django 6.0.3 on 2026-09-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('sehir', models.CharField(blank=True, max_length=50, verbose_name='Şehir')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatarlar/%Y/%m/', verbose_name='Profil Fotoğrafı')),
                ('biyografi', models.TextField(blank=True, verbose_name='Hakkında')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profiller',
                'db_table': 'ml_model_profilmodel',
                'indexes': [models.Index(fields=['kullanici'], name='ml_model_pr_kullani_12d866_idx'), models.Index(fields=['is_active'], name='ml_model_pr_is_acti_495df6_idx')],
            },
        ),
    ]
